name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --prune --unshallow --tags
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
    - name: Pack
      run: dotnet pack ./src -c Release /p:Version=$GITVERSION_SEMVER
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: JWT.Cli.v{$GITVERSION_SEMVER}
        path: ./src/JWT.Cli/nupkg/*.nupkg
